/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppMasthead: typeof import('./components/AppMasthead.vue')['default']
    AppPagination: typeof import('./components/AppPagination.vue')['default']
    Badge: typeof import('./components/Badge.vue')['default']
    ComposerTips: typeof import('./components/ComposerTips.vue')['default']
    CoverImage: typeof import('./components/CoverImage.vue')['default']
    DynamicForm: typeof import('./components/DynamicForm.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EthnicCard: typeof import('./components/EthnicCard.vue')['default']
    EthnicHistoryView: typeof import('./components/EthnicHistoryView.vue')['default']
    EthnicMap: typeof import('./components/EthnicMap.vue')['default']
    FeatureCard: typeof import('./components/FeatureCard.vue')['default']
    ImageCreditBadge: typeof import('./components/ImageCreditBadge.vue')['default']
    ImageCredits: typeof import('./components/ImageCredits.vue')['default']
    InteractionBar: typeof import('./components/InteractionBar.vue')['default']
    InterestPicker: typeof import('./components/InterestPicker.vue')['default']
    LinkedDiscussion: typeof import('./components/LinkedDiscussion.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    LoginDialog: typeof import('./components/LoginDialog.vue')['default']
    MachineTranslationNotice: typeof import('./components/MachineTranslationNotice.vue')['default']
    MentionTextarea: typeof import('./components/MentionTextarea.vue')['default']
    PageHead: typeof import('./components/PageHead.vue')['default']
    PopulationViz: typeof import('./components/PopulationViz.vue')['default']
    RecommendationPanel: typeof import('./components/RecommendationPanel.vue')['default']
    Reveal: typeof import('./components/Reveal.vue')['default']
    RichArticle: typeof import('./components/RichArticle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionRule: typeof import('./components/SectionRule.vue')['default']
    SourceReferences: typeof import('./components/SourceReferences.vue')['default']
    SubscribeButton: typeof import('./components/SubscribeButton.vue')['default']
    TranslateButton: typeof import('./components/TranslateButton.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
    UserContent: typeof import('./components/UserContent.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
